### ISSUE TITLE
TypeError: this.state.posts is undefined, in PostsManager.js

### ISSUE THREAD

**Issue by gitxav** [oktadeveloper/okta-react-node-example#1]
Hi all:

A really nice application but unfortunately crashes when trying to access posts, with the following error:

![react-okta-screenshot from 2018-11-26 11-38-11](https://user-images.githubusercontent.com/11687381/49045898-fce4aa00-f197-11e8-80a0-351d8182e9e7.jpg)

My package.json file is:

{
  "name": "okta-node-react-example",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@material-ui/core": "^1.3.1",
    "@material-ui/icons": "^1.1.0",
    "@okta/jwt-verifier": "^0.0.12",
    "@okta/okta-react": "^1.1.4",
    "body-parser": "^1.18.3",
    "cors": "^2.8.4",
    "dotenv": "^6.0.0",
    "epilogue": "^0.7.1",
    "express": "^4.16.3",
    "final-form": "^4.8.3",
    "lodash": "^4.17.10",
    "moment": "^2.22.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-final-form": "^3.7.0",
    "react-router-dom": "^4.3.1",
    "react-scripts": "1.1.4",
    "recompose": "^0.27.1",
    "sequelize": "^4.38.0",
    "react-router": "^4.0.0",
    "prop-types": "^15.6.2"
  },
  "scripts": {
    "start": "npm-run-all --parallel watch:server start:web",
    "start:web": "react-scripts start",
    "start:server": "node src/server",
    "watch:server": "nodemon --watch src/server src/server",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "npm-run-all": "^4.1.3"
  }
}

I'm working with ubuntu 16.04, node v8.11.2 and yarn v1.12.3

Thanks in advance for any hint to fix it.

**Comment by redbmk** [comment]
Hi @gitxav, sorry for the late reply! I don't see `sqlite` (or `sqlite3`) as a dependency in your package.json. Can you try `yarn add sqlite3` and see if that fixes it?

**Comment by redbmk** [comment]
@gitxav I pushed an update that will prevent the crash and show an error. Were you able to get this to work by checking that you have `sqlite`/`sqlite3` installed on your machine (e.g. `which sqlite3`) as well as running `yarn add sqlite3`?
