### ISSUE TITLE
posts/new route doesn't work

### ISSUE THREAD

**Issue by ironcove** [oktadeveloper/okta-react-node-example#2]
I cloned code as it. Set up Okta and created .env.local
Login and logout works as expected
Click on Posts Manager and then click add post
Just goes to a new blank screen. No error.
I experimented after with updating packages but no luck.
Any ideas on how to get this working?

**Comment by redbmk** [comment]
Can you check if you have `sqlite` installed? I just added it to the readme as a prerequisite, but I think that might be the issue. If you're on mac or linux try `which sqlite3` or `which sqlite`. It should return a path like `/usr/bin/sqlite3`. If it doesn't return anything you might need to [install sqlite](https://www.sqlite.org/index.html) for this to work.

**Comment by redbmk** [comment]
@ironcove were you able to get this to work? would be nice to confirm you have sqlite installed.

**Comment by kingluddite** [comment]
@redbmk Yes I installed sqlite with homebrew and it now works. I did a fresh install and followed your README exactly. Thanks for the follow up!

**Comment by ironcove** [comment]
@redbmk Yes that was it. I installed sqlite with Homebrew, did a fresh clone of your repo and followed your README instructions verbatim and it works fine. Thanks for the follow up!

**Comment by redbmk** [comment]
Awesome, glad it's working now :)
